.PHONY:all

all:
	@echo "CC = $(CC)"
	@echo "AS = $(AS)"
	@echo "CXX = $(CXX)"
	@echo "AR  = $(AR)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "ASFLAGS = $(ASFLAGS)"
	@echo "ARFLAGS = $(ARFLAGS)"
	@echo "LDFLAGS = $(LDFLAGS)"




















