.PHONY : single_list single_list_test clean
single_list:
	gcc single_list.c -D QUEUE -o single_list.out

single_list_test:
	gcc single_list_test.c -o single_list_test.out

single_list:
	gcc single_list.c -D QUEUE -o single_list.out

single_list:
	gcc single_list.c -D QUEUE -o single_list.out


clean:
	rm *.out