.PHONY:all clean

all:
	cp ../resources_file/access.log .
	cp ../resources_file/error.log .
	cp ../resources_file/passwd.txt .
	cp ../resources_file/person_weight_hright.txt .
	cp ../resources_file/1.txt .

clean:
	rm *.txt
	rm *.log