
STR := $(STR2)
STR = hello
STR2 = hello
STR2 += world


test1 = a
test1 ?= b
test2 = c

all:
	@echo "STR = $(STR)"
	@echo "STR2 = $(STR2)"
	@echo 'STR2 = $(STR2)'
	@echo "test1 = $(test1)"
	@echo "test2 = $(test2)"

